

name: serviciomysql
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ROOT_PASSWORD: example
        ports:
          - 3306:3306
  
    steps:
 
      - name: Run a one-line script
        run: echo Hello, world!

    

